# This is just the content from the lecture for learning purpose.
# I will instead use Github Action so this file is not directly used.

# Telling travis that we need sudo level
sudo: required
language: generic
# Tell travis to install docker
services:
  - docker

# Before doing tests
before_install:
  - docker build -t sayyoungman/docker-react -f Dockerfile.dev .  # Tag it to refer to it later

# Contain all the commands that is required to run tests
script:
  - docker run -e CI=true sayyoungman/docker-react npm run test

# Tell travis how to deploy the app to AWS
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-908947314471"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"