FROM node:16-alpine

WORKDIR "/app"

COPY ["7. Continuous Integration and Deployment with AWS/frontend/package.json", "."]

RUN npm install

ADD ["7. Continuous Integration and Deployment with AWS/frontend", "./"]

CMD ["npm", "run", "start"]